version: '3'

services:
  postgres:
    image: postgres:16
    container_name: facturation_postgres
    restart: always
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel
      POSTGRES_DB: facturation
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - facturation_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: facturation_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - facturation_network

networks:
  facturation_network:
    driver: bridge

volumes:
  postgres_data:
